create_clock -name clk_32m -period 31.25 [get_ports clk_32m]
create_clock -name SPI_SCK -period 100.0 [get_ports SPI_SCK]
set_input_delay -max 2.0 -clock clk_32m [get_ports {SPI_MOSI reg_rdata fw_ld_rdata fw_ld_ready}]
set_input_delay -min 1.0 -clock clk_32m [get_ports {SPI_MOSI reg_rdata fw_ld_rdata fw_ld_ready}]
set_output_delay -max 2.0 -clock clk_32m [all_outputs]
set_output_delay -min 0.0 -clock clk_32m [all_outputs]
set_clock_uncertainty 0.25 [get_clocks clk_32m]
set_false_path -from [get_ports rst_n]
set_false_path -from [get_ports HOST_CS]
set_clock_groups -asynchronous -group [get_clocks clk_32m] -group [get_clocks SPI_SCK]
