#!/usr/bin/env python3
"""Derive an MCP-free ("honest") SDC from a scoped signoff SDC.

Question this exists to answer: the 4.5 V-core closure (job 3738, WNS 0 / TNS 0
at max_ss_125C_4v50) was measured with `pnr_32m_scoped_v25_b6.sdc`, which
carries 27 `set_multicycle_path` statements. Nobody has checked whether 4.5 V
still closes when every one of those relaxations is withdrawn. If it does, the
whole MCP apparatus -- Open Risks #43's remaining settling proofs, the audit
machinery, the #39/#40 cone-scoping work -- stops being tapeout-critical.

What is stripped: every `set_multicycle_path` (setup and hold alike).

What is KEPT, deliberately:
  * `set_false_path -from [get_ports RESETB|HOST_CS|SPI_SCK]` -- these are
    genuinely asynchronous inputs, not timing relaxations. Constraining them
    would be modelling a path that does not exist.
  * `set_false_path -through $dbg_nets` -- debug plumbing, same argument.
  * every clock definition, IO delay, and max_transition constraint.
So the output isolates exactly one variable: the multicycle exceptions.

Lines are commented out rather than deleted, and the collection `set`
statements that fed them are left in place, so the result diffs cleanly against
the source and the reader can see precisely what was withdrawn.
"""
import argparse
import re
import sys

MARK = "#HONEST-STRIPPED# "


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    src_lines = open(args.src).read().split("\n")
    out, n = [], 0
    in_continuation = False
    for line in src_lines:
        stripped = line.strip()
        is_mcp = bool(re.match(r"set_multicycle_path\b", stripped))
        if is_mcp or in_continuation:
            out.append(MARK + line)
            if is_mcp:
                n += 1
            # A trailing backslash continues the command onto the next line.
            in_continuation = stripped.endswith("\\")
            continue
        out.append(line)

    if n == 0:
        sys.exit(f"ERROR: no set_multicycle_path found in {args.src} -- wrong file?")

    header = [
        "# GENERATED by gen_honest_sdc.py -- DO NOT EDIT BY HAND",
        f"# Source: {args.src}",
        f"# {n} set_multicycle_path statements withdrawn (commented with '{MARK.strip()}').",
        "# Async-port and debug-net false paths, clocks, IO delays and",
        "# max_transition are all retained -- see the script docstring for why.",
        "# Purpose: measure timing with NO multicycle relaxation, to test whether",
        "# the 4.5 V core closes honestly (Open Risks #1/#43/#44).",
        "",
    ]
    with open(args.out, "w") as fh:
        fh.write("\n".join(header + out) + "\n")
    print(f"wrote {args.out}: {n} set_multicycle_path statements withdrawn")


if __name__ == "__main__":
    main()
