create_clock -name clk_32m -period 31.25 [get_ports clk_32m]
set_input_delay -max 2.0 -clock clk_32m [get_ports {iq_i_0 iq_i_1 iq_i_2 iq_i_3 iq_q_0 iq_q_1 iq_q_2 iq_q_3 iq_valid sf sc_lock}]
set_input_delay -min 1.0 -clock clk_32m [get_ports {iq_i_0 iq_i_1 iq_i_2 iq_i_3 iq_q_0 iq_q_1 iq_q_2 iq_q_3 iq_valid sf sc_lock}]
set_output_delay -max 2.0 -clock clk_32m [all_outputs]
set_output_delay -min 0.0 -clock clk_32m [all_outputs]
set_clock_uncertainty 0.25 [get_clocks clk_32m]
set_false_path -from [get_ports rst_n]
set_false_path -hold -from [all_inputs]
set_false_path -hold -to [all_outputs]
