create_clock -name clk -period 31.25 [get_ports clk]
set_input_delay -max 2.0 -clock clk [get_ports {iq_valid raw_i0 raw_i1 raw_i2 raw_i3 raw_q0 raw_q1 raw_q2 raw_q3 sc_lock timing_ref sf ref_sel}]
set_input_delay -min 1.0 -clock clk [get_ports {iq_valid raw_i0 raw_i1 raw_i2 raw_i3 raw_q0 raw_q1 raw_q2 raw_q3 sc_lock timing_ref sf ref_sel}]
set_output_delay -max 2.0 -clock clk [all_outputs]
set_output_delay -min 0.0 -clock clk [all_outputs]
set_clock_uncertainty 0.25 [get_clocks clk]
set_false_path -from [get_ports rst_n]
set_false_path -hold -from [all_inputs]
set_false_path -hold -to [all_outputs]
