create_clock -name clk_32m -period 31.25 [get_ports clk_32m]
set_input_delay -max 2.0 -clock clk_32m [get_ports {energy_sum_0 energy_sum_1 energy_sum_2 energy_sum_3 noise_sample_en sf noise_alpha_shift sigma2_sw_0 sigma2_sw_1 sigma2_sw_2 sigma2_sw_3 sigma2_commit sigma2_src agc_gain_changed}]
set_input_delay -min 1.0 -clock clk_32m [get_ports {energy_sum_0 energy_sum_1 energy_sum_2 energy_sum_3 noise_sample_en sf noise_alpha_shift sigma2_sw_0 sigma2_sw_1 sigma2_sw_2 sigma2_sw_3 sigma2_commit sigma2_src agc_gain_changed}]
set_output_delay -max 2.0 -clock clk_32m [all_outputs]
set_output_delay -min 0.0 -clock clk_32m [all_outputs]
set_clock_uncertainty 0.25 [get_clocks clk_32m]
set_false_path -from [get_ports rst_n]
set_false_path -hold -from [all_inputs]
set_false_path -hold -to [all_outputs]
