create_clock -name clk_32m -period 31.25 [get_ports clk_32m]
set_input_delay -max 2.0 -clock clk_32m [get_ports {s_addr s_wdata s_we s_re sx_start sx_rnw sx_target sx_addr_in sx_wdata_in SPI_MISO}]
set_input_delay -min 1.0 -clock clk_32m [get_ports {s_addr s_wdata s_we s_re sx_start sx_rnw sx_target sx_addr_in sx_wdata_in SPI_MISO}]
set_output_delay -max 2.0 -clock clk_32m [all_outputs]
set_output_delay -min 0.0 -clock clk_32m [all_outputs]
set_clock_uncertainty 0.25 [get_clocks clk_32m]
set_false_path -from [get_ports rst_n]
