create_clock -name clk_32m -period 31.25 [get_ports clk_32m]
create_clock -name clk_16m -period 62.5  [get_ports clk_16m]
set_clock_groups -asynchronous -group [get_clocks clk_32m] -group [get_clocks clk_16m]
set_input_delay  -max 2.0 -clock clk_32m [get_ports {iq_in_i iq_in_q decim_ratio}]
set_input_delay  -min 1.0 -clock clk_32m [get_ports {iq_in_i iq_in_q decim_ratio}]
set_output_delay -max 2.0 -clock clk_16m [all_outputs]
set_output_delay -min 0.0 -clock clk_16m [all_outputs]
set_clock_uncertainty 0.25 [get_clocks clk_32m]
set_clock_uncertainty 0.25 [get_clocks clk_16m]
set_false_path -from [get_ports rst_n]
